#!/usr/bin/env python

import commands
import re
import sys


def make_re(*msgs):
    return re.compile('(%s)' % '|'.join(msgs))

pyflakes_ignore = make_re(
    'unable to detect undefined names',
    'Unable to import',
)
pyflakes_warning = make_re(
    'imported but unused',
    'is assigned to but never used',
    'redefinition of unused',
    'at least two spaces before inline comment',
)
# E221,E701,E202
pep8_ignore = []
pep8_warning = make_re('.')

# https://bitbucket.org/logilab/pylint/src/2dc4a9def934/epylint.py?at=default
epylint_warning = make_re(
    'fixme',
    'star-args',
    'protected-access',
    'bad-builtin',
    'anomalous-backslash-in-string',
    'broad-except',
    'pointless-statement',
    'expression-not-assigned',
)

def run(cmd, ignore_re, warning_re):
    output = commands.getoutput(cmd)
    for line in output.splitlines():
        if ignore_re and ignore_re.search(line):
            continue
        if ': ' in line and warning_re and warning_re.search(line):
            line = '%s: Warning %s' % tuple(line.split(': ', 1))
        print line

run('epylint %s 2>/dev/null' % sys.argv[1], None, epylint_warning)
run('pyflakes %s' % sys.argv[1], pyflakes_ignore, pyflakes_warning)

pep8_ignore = ' '.join('--ignore=%s' % i for i in pep8_ignore)
run("pep8 %s --format '%%(path)s:%%(row)d: %%(text)s' %s" %
    (pep8_ignore, sys.argv[1]), None, pep8_warning)
